Always pass full paths to kitchen.sh.
Avoids errors like the following:

$ ./ppi_build.sh mifos mifos_ppi_dw path/to/pentaho-data-integration MYSQL_ARGS
Initializing OLTP database (mifos)...
Initializing data warehouse (mifos_ppi_dw)...
Running ETL...
INFO  16-11 11:51:07,401 - Using "/tmp/vfs_cache" as temporary files store.
INFO  16-11 11:51:08,301 - Kitchen - Kitchen
Processing stopped because of an error:
Unable to load the job from XML file [./JohnWoodlockWorkInProgress/MifosDataWarehouseETL/CreateDataWarehouse.kjb]

Unable to read file [file:///path/to/pentaho-data-integration/JohnWoodlockWorkInProgress/MifosDataWarehouseETL/CreateDataWarehouse.kjb]
Could not read from "file:///path/to/pentaho-data-integration/JohnWoodlockWorkInProgress/MifosDataWarehouseETL/CreateDataWarehouse.kjb" because it is a not a file.

ERROR: Kitchen can't continue because the job couldn't be loaded.
No errors found.